repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.2.0
        hooks:
            -   id: end-of-file-fixer
            -   id: trailing-whitespace
            -   id: check-merge-conflict

    -   repo: https://github.com/commitizen-tools/commitizen
        rev: v2.24.0
        hooks:
            -   id: commitizen
                stages: [ commit-msg ]

    -   repo: https://github.com/PyCQA/isort
        rev: 5.10.1
        hooks:
            -   id: isort
