apiVersion: apps/v1
kind: Deployment
metadata:
    name: drf-api
    labels:
        app: drf-api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: drf-api
    template:
        metadata:
            labels:
                app: drf-api
        spec:
            containers:
                -   name: drf-api
                    image: pplmx/drf_sample
                    ports:
                        -   containerPort: 8000
                    imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
    name: drf-api-svc
spec:
    selector:
        app: drf-api
    ports:
        -   protocol: "TCP"
            port: 3000
            targetPort: 8000
    type: LoadBalancer
