apiVersion: apps/v1
kind: Deployment
metadata:
    name: drf-api
    labels:
        app: drf-api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: drf-api
    template:
        metadata:
            labels:
                app: drf-api
        spec:
            containers:
                -   name: drf-api
                    image: pplmx/drf_sample
                    env:
                        - name: DJANGO_SUPERUSER_USERNAME
                          value: admin
                        - name: DJANGO_SUPERUSER_PASSWORD
                          value: admin
                        - name: DJANGO_SUPERUSER_EMAIL
                          value: admin@admin.io
                    ports:
                        -   containerPort: 8000
                    imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
    name: drf-api-svc
spec:
    selector:
        app: drf-api
    ports:
        -   protocol: "TCP"
            port: 3000
            targetPort: 8000
    type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: minikube-ingress
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
    rules:
        -   host: drf.info
            http:
                paths:
                    -   path: /
                        pathType: Prefix
                        backend:
                            service:
                                name: web
                                port:
                                    number: 80
