version: Compose specification
services:
    app:
        # or maybe you can use this "ghcr.io/pplmx/drf_sample"
        image: pplmx/drf_sample
        ports:
            - "8000:8000"
        restart: always
        networks:
            - sample_net
        env_file:
            - .env
        depends_on:
            - db
    db:
        image: postgres
        ports:
            - "5432:5432"
        restart: always
        networks:
            - sample_net
        env_file:
            - .env
networks:
    sample_net:
        name: sample_net
        ipam:
            config:
                -   subnet: 172.16.133.0/24
