version: Compose specification
services:
    app:
        # or maybe you can use this "ghcr.io/pplmx/drf_sample"
        image: pplmx/drf_sample
        ports:
            - "8000:8000"
        restart: always
