version: Compose specification
services:
    app:
        image: pplmx/djgo
        ports:
            - "8000:8000"
        restart: always
        environment:
            - DJANGO_SUPERUSER_USERNAME=admin
            - DJANGO_SUPERUSER_PASSWORD=admin
            - DJANGO_SUPERUSER_EMAIL=admin@cc.io
