version: Compose specification
services:
    app:
        # or maybe you can use this "ghcr.io/pplmx/drf_sample"
        image: pplmx/drf_sample
        ports:
            - "8000:8000"
        restart: always
        networks:
            - sample_net
        env_file:
            - .env
        depends_on:
            - db
    db:
        image: mariadb
        ports:
            - "3306:3306"
        restart: always
        networks:
            - sample_net
        env_file:
            - .env
networks:
    sample_net:
