version: Compose specification
services:
    app:
        # or maybe you can use this "ghcr.io/pplmx/drf_sample"
        image: pplmx/drf_sample
        ports:
            - "8000:8000"
        restart: always
        environment:
            - DJANGO_SUPERUSER_USERNAME=admin
            - DJANGO_SUPERUSER_PASSWORD=admin
            - DJANGO_SUPERUSER_EMAIL=admin@cc.io
