name: Image Builder

on:
    workflow_dispatch:  # Manual trigger
    push:
        branches: [ main ]
        tags: [ "v*.*.*" ]  # Semantic version tags
    pull_request:
        branches: [ main ]

# Define environment variables for reuse
env:
    REGISTRY_DOCKERHUB: docker.io
    REGISTRY_GHCR: ghcr.io
    IMAGE_NAME: drf_sample
    PLATFORMS: linux/amd64,linux/arm64

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write  # Required for GHCR push

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Generate Docker metadata
                id: meta
                uses: docker/metadata-action@v5
                with:
                    images: |
                        ${{ env.REGISTRY_DOCKERHUB }}/pplmx/${{ env.IMAGE_NAME }}
                        ${{ env.REGISTRY_GHCR }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
                    tags: |
                        type=raw,value=latest,enable={{is_default_branch}}
                        type=ref,event=pr
                        type=semver,pattern={{version}}
                        type=semver,pattern={{major}}.{{minor}}
                        type=semver,pattern={{major}}

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
                with:
                    platforms: ${{ env.PLATFORMS }}

            # Login to Docker Hub if pushing a release
            -   name: Login to Docker Hub
                if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
                uses: docker/login-action@v3
                with:
                    registry: ${{ env.REGISTRY_DOCKERHUB }}
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            # Login to GitHub Container Registry if pushing a release
            -   name: Login to GitHub Container Registry
                if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
                uses: docker/login-action@v3
                with:
                    registry: ${{ env.REGISTRY_GHCR }}
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            # Build and push Docker image
            -   name: Build and push Docker image
                uses: docker/build-push-action@v6
                with:
                    context: .
                    platforms: ${{ env.PLATFORMS }}
                    push: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
                    cache-from: type=gha  # Use GitHub Actions cache
                    cache-to: type=gha,mode=max  # Maximize cache usage
