name: Image Builder

on:
    # Allows running manually
    workflow_dispatch:
    push:
        branches:
            # - '**' # all branches
            - 'main' # if push to the main branch
        tags:
            - "v*.*.*" # match v1.0.0, v2.0.0, v1.0.0-alpha, v1.0.0-alpha.1, v2.0.0-rc.1+build.1, etc.
    pull_request:
        branches:
            - "main" # if pr to the main branch

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
            -   name: Docker meta
                id: meta
                uses: docker/metadata-action@v5
                with:
                    # list of Docker images to use as base name for tags
                    images: |
                        pplmx/drf_sample
                        ghcr.io/pplmx/drf_sample
                    # generate Docker tags based on the following events/attributes
                    tags: |
                        # set latest tag for default branch
                        type=raw,value=latest,enable={{is_default_branch}}
                        type=ref,event=pr
                        type=semver,pattern={{version}}
                        type=semver,pattern={{major}}.{{minor}}
                        type=semver,pattern={{major}}
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            -   name: Login to Docker Hub
                # only log in when push event is a tag
                if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -   name: Login to GitHub Container Registry
                # only log in when push event is a tag
                if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GITHUB_TOKEN }}
            -   name: Build and push
                uses: docker/build-push-action@v5
                with:
                    context: .
                    platforms: linux/amd64,linux/arm64
                    # only push when push event is a tag
                    push: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
